# application-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbname
    username: name
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true