# application-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagerDB
    username: anis
    password: anis1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true