CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255) CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6),
    description VARCHAR(255),
    status      VARCHAR(255) CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
    title       VARCHAR(255),
    user_id     BIGINT REFERENCES users(id)
);
